### ISSUE TITLE
Ampersand in `enclosure` not escaped, causing the feed to be invalid

### ISSUE THREAD

**Issue by dzx-dzx** [etabits/apodrss#1]
The recent RSS feed includes:
```xml
<enclosure url="https://apod.nasa.gov/apod/image/2407/GianniTumino_Etna&MW_14mm_JPG_LOGO__1024pix.jpg" length="0" type="image/jpg"/>
```
which contains an `&` which renders it invalid.
Rather concidentally, the latest pull request for the upstream `feed` package is just about that: https://github.com/jpmonette/feed/pull/193

**Comment by aularon** [comment]
Pull request has been merged! Thank you for your contribution :pray:

**Comment by dzx-dzx** [comment]
Thank you! Do you have any idea when it will be adopted by the apod site?

**Comment by aularon** [comment]
I guess (hope) before weekend. I communicated the update to APOD server maintainers so it shouldn't take long. You may use https://apod.me/en.rss _temporarily_ until the _official_ https://apod.com/feed.rss starts generating with the new code! Best :pray:

**Comment by dzx-dzx** [comment]
Thanks!
